#!/usr/bin/env bash
#Script that displays the content of /etc/passwd
IFS=":"
while read -r username password userid groupid comment homedir shell; do 
	echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by passcode $password, more info about the user here: $username" 
done < "/etc/passwd"	
