#!/usr/bin/env bash
#Script that displays the content of the file /etc/passwd
while IFS=':' read -r username password user_id group_id user_info home_directory shell; do
    echo "The user $username is part of the $group_id gang, lives in $home_directory and rides $shell."
    echo "User ID's place is protected by passcode $password, more info about the user here: $user_info"
    echo "--------------------------------------------------"
done < /etc/passwd
