#!/usr/bin/env bash
#Script that displays messages when read some signals 

PID_FILE="/var/run/myscript.pid"
echo $$ > "$PID_FILE"
trap 'rm -f "$PID_FILE"; exit' SIGQUIT
trap 'echo "I hate the kill command"; exit' SIGTERM
trap 'echo "Y U no love me?!";' SIGINT
while true 
do 
	echo "To infinity and beyond" 
	sleep 2
done
